server:
    port: 8080


spring:
    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/star_node_mill?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        ###################以下为druid增加的配置###########################
        type: com.alibaba.druid.pool.DruidDataSource
        # 下面为连接池的补充设置，应用到上面所有数据源中
        # 初始化大小，最小，最大
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters:
            commons-log.connection-logger-name: stat,wall,log4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        # 合并多个DruidDataSource的监控数据
        useGlobalDataSourceStat: true
        ###############以上为配置druid添加的配置########################################

    #redis集群
    redis:
        host: 127.0.0.1
        port: 6379
        # 连接超时时间（毫秒）
        timeout: 20000
        #    集群环境打开下面注释，单机不需要打开
        #    cluster:
        #      集群信息
        #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
        #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
        #      maxRedirects: 3
        pool:
            # 连接池最大连接数（使用负值表示没有限制）
            max-active: 8
            # 连接池中的最小空闲连接
            min-idle: 0
            # 连接池中的最大空闲连接
            max-idle: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制)
            max-wait: -1
        password:
    application:
        name: spring-boot-redis

#mybatis:
#    mapper-locations: classpath:mapping/*Mapper.xml
#    type-aliases-package: com.mg.sn.mill.model.*
#logging:
#    level:
#        com.hcy.shiro.mva.mapper: debug

mybatis-plus:
    mapper-locations: classpath:mapping/*Mapper.xml
    # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
#    type-aliases-package: com.mg.sn.mill.model.*
    # 该配置请和 typeAliasesPackage 一起使用，如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象 。
    type-aliases-super-type: java.lang.Object
    configuration:
        # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        # 驼峰下划线转换
        map-underscore-to-camel-case: true
        # 配置的缓存的全局开关
        cache-enabled: true
        # 延时加载的开关
        lazy-loading-enabled: true
        # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
        multiple-result-sets-enabled: true
        use-generated-keys: true
        default-statement-timeout: 60
        default-fetch-size: 100

logging:
    path: /Users/jackie/workspace/rome/
#    file: springbootdemo.log